spring:
  datasource:
    url: jdbc:mysql://你的JDBC URL
    username: 账号
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:static/, file:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.nju.notebook.entity


file:
  maxUploadSizeMB: 10
  savePath: img
server:
  port: 8999

