spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: Allen
    password: qweasd
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:static/, file:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.notebook2019.entity

server:
  port: 8888